### PR TITLE
Change namespace of IO::Buffer to Coolio::Buffer

### PR DESCRIPTION
**Pull request by Watson1978**
The `IO::Buffer` class was introduced at Ruby 3.1.
Ref: https://bugs.ruby-lang.org/issues/18020

The cool.io gem has same name class and it has been conflicted. If you used unknowingly, it will overwrite Ruby's IO::Buffer and it might cause problems.

So, this patch will add namespece that it can be used as `Coolio::Buffer`.

Related to https://github.com/fluent/fluentd/pull/4619

## Types of Changes

- Bug fix.

## Contribution

- [ ] I added tests for my changes.
- [x] I tested my changes locally.
- [x] I agree to the [Developer's Certificate of Origin 1.1](https://developercertificate.org/).

### CODE REVIEW

**Comment by Watson1978** [comment]
@ioquatix Could you please review this PR?

Thanks

**Comment by ioquatix** [comment]
I'm okay with this, but to avoid the namespace confusion, what do you think about renaming it to `Coolio::Buffer`.

Using `Coolio::IO::Buffer` means anyone who writes `IO` inside `module Coolio` will now get something different.

**Comment by Watson1978** [comment]
@ioquatix Thank you for your review.
I renamed to `Coolio::Buffer` and move `iobuffer.c` into `cool.io` because it has same namespace.

Thanks.

**Review by ioquatix — APPROVED** [review]
This looks great to me, thanks for your effort and implementing the requested changes.

**Comment by ioquatix** [comment]
I suppose we can make a minor release for this change.

**Comment by Watson1978** [comment]
Thank you!!
OK, I will test cool.io gem v1.9.0 using Fluentd's CI.

If it works as expected, all tests will be successful.
https://github.com/fluent/fluentd/pull/4619

**Pull request merged**
